#!/bin/bash

echo "Starting P2P Chat Test"
echo "====================="
echo ""
echo "This script will demonstrate the true P2P nature of the chat application."
echo ""
echo "Open two terminal windows and run:"
echo ""
echo "Terminal 1:"
echo "  cargo run -- 8080 127.0.0.1:8081"
echo ""
echo "Terminal 2:"
echo "  cargo run -- 8081 127.0.0.1:8080"
echo ""
echo "Notice that:"
echo "- Both peers specify each other's addresses"
echo "- Either peer can start first"
echo "- Both peers listen AND attempt to connect"
echo "- The connection is established regardless of start order"
echo ""
echo "This is true P2P - no fixed client/server roles!"